### ISSUE TITLE
Після зміни статусу з "unavailable" на "safe" спрацьовує відбій тривоги

### ISSUE THREAD

**Issue by VahaC** [lufton/ha-blueprints#2]
Після зміни статусу з "unavailable" на "safe" спрацьовує відбій тривоги.
Це призводить до частих нотифікацій при не стабільному підключенні до інтернету.
Чи можливо зробити перевірку щоб перехід з статусу "unavailable" ігнорувався?

**Comment by tolixx** [comment]
```
- alias: Alert raised
    platform: state
    id: sensor_change
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"
    entity_id: !input alert_sensors
```

Я зробив для себе ось таку правку й тепер все працює як треба.
